package app.extremecardriving.patches.currency

import app.morphe.patcher.extensions.InstructionExtensions.addInstructions
import app.morphe.patcher.patch.bytecodePatch
import app.extremecardriving.patches.shared.Constants.COMPATIBILITY_ECD

@Suppress("unused")
val ecdCurrencyPatch = bytecodePatch(
    name = "Extreme Car Driving Unlimited Currencies",
    description = "Sets all in-game currencies (diamonds, coins, upgrade points) to 999,999,999 via IL2CPP API.",
    default = true
) {
    compatibleWith(COMPATIBILITY_ECD)

    execute {
        OnCreateFingerprint.method.addInstructions(0, """
            invoke-virtual {p0}, Landroid/content/Context;->getFilesDir()Ljava/io/File;
            move-result-object v3
            new-instance v4, Ljava/io/File;
            const-string v5, "libcurrencyhack.so"
            invoke-direct {v4, v3, v5}, Ljava/io/File;-><init>(Ljava/io/File;Ljava/lang/String;)V
            invoke-virtual {v4}, Ljava/io/File;->exists()Z
            move-result v3
            if-nez v3, :currency_hack_loaded
            new-instance v3, Ljava/lang/StringBuilder;
            invoke-direct {v3}, Ljava/lang/StringBuilder;-><init>()V
            const-string v5, "f0VMRgIBAQAAAAAAAAAAAAMAtwABAAAAAAAAAAAAAABAAAAAAAAAAIgpAAAAAAAAAAAAAEAAOAAJAEAAGgAYAAYAAAAEAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAA+AEAAAAAAAD4AQAAAAAAAAgAAAAAAAAAAQAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQGwAAAAAAAFAbAAAAAAAAAEAAAAAAAAABAAAABgAAAFAbAAAAAAAAUFsAAAAAAABQWwAAAAAAABADAAAAAAAAsAQAAAAAAAAAQAAAAAAAAAEAAAAGAAAAYB4AAAAAAABgngAAAAAAAGCeAAAAAAAABAAAAAAAAAB4AAAAAAAAAABAAAAAAAAAAgAAAAYAAAA4HAAAAAAAADhcAAAAAAAAOFwAAAAAAADAAQAAAAAAAMABAAAAAAAACAAAAAAAAABS5XRkBAAAAFAbAAAAAAAAUFsAAAAAAABQWwAAAAAA"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "ABADAAAAAAAAsAQAAAAAAAABAAAAAAAAAFDldGQEAAAAmA8AAAAAAACYDwAAAAAAAJgPAAAAAAAAXAAAAAAAAABcAAAAAAAAAAQAAAAAAAAAUeV0ZAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAADgCAAAAAAAAOAIAAAAAAAA4AgAAAAAAAJgAAAAAAAAAmAAAAAAAAAAEAAAAAAAAAAgAAACEAAAAAQAAAEFuZHJvaWQAGAAAAHIyOQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxNDIwNjg2NQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAABIA"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "AAAAAAAAAAAAAAAAAAAAAAAAEAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAHQAAABIAAAAAAAAAAAAAAAAAAAAAAAAALwAAABIAAAAAAAAAAAAAAAAAAAAAAAAAQwAAABIAAAAAAAAAAAAAAAAAAAAAAAAAUgAAABIAAAAAAAAAAAAAAAAAAAAAAAAAYQAAABIAAAAAAAAAAAAAAAAAAAAAAAAAlwAAABIAAAAAAAAAAAAAAAAAAAAAAAAAngAAABIAAAAAAAAAAAAAAAAAAAAAAAAApAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAZwAAABIADAAgEgAAAAAAAAQAAAAAAAAAAAACAAIAAgADAAIAAgACAAQABAAEAAEAAQABAKwAAAAwAAAAEAAAAAEAAQC6AAAAMAAAABAAAAABAAEAywAAADAAAAAAAAAAYw0FAAAABAC1AAAAAAAAADdxDQUAAAMAxAAAAAAAAABjDQUAAAACALUAAAAA"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "AAAAAQAAAAsAAAABAAAAGgAAAAAAAAEAAgAACwAAAOkNWGIAX19jeGFfZmluYWxpemUAX19jeGFfYXRleGl0AF9fcmVnaXN0ZXJfYXRmb3JrAF9fYW5kcm9pZF9sb2dfcHJpbnQAcHRocmVhZF9jcmVhdGUAcHRocmVhZF9kZXRhY2gAc2xlZXAASmF2YV9jb21fYWltX0V4dHJlbWVBY3Rpdml0eV9uYXRpdmVDdXJyZW5jeUhhY2sAZGxvcGVuAGRsc3ltAGRsZXJyb3IAbGliZGwuc28ATElCQwBsaWJsb2cuc28ATElCTE9HAGxpYmMuc28AL2RhdGEvZGF0YS9jb20udGVybXV4L2ZpbGVzL3Vzci9iaW4vLi4vLi4vdXNyL2xpYgBsaWJhbmRyb2lkLnNvAAAAAAAAUFsAAAAAAAADBAAAAAAAAFBbAAAAAAAAWFsAAAAAAAADBAAAAAAAAC4MAAAAAAAAYFsAAAAAAAADBAAA"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "AAAAAMsLAAAAAAAAaFsAAAAAAAADBAAAAAAAACEOAAAAAAAAcFsAAAAAAAADBAAAAAAAACQKAAAAAAAAeFsAAAAAAAADBAAAAAAAACoOAAAAAAAAgFsAAAAAAAADBAAAAAAAAMgJAAAAAAAAiFsAAAAAAAADBAAAAAAAAFsNAAAAAAAAkFsAAAAAAAADBAAAAAAAANIJAAAAAAAAmFsAAAAAAAADBAAAAAAAANwJAAAAAAAAoFsAAAAAAAADBAAAAAAAAA8PAAAAAAAAqFsAAAAAAAADBAAAAAAAAMsOAAAAAAAAsFsAAAAAAAADBAAAAAAAABQPAAAAAAAAuFsAAAAAAAADBAAAAAAAAHIMAAAAAAAAwFsAAAAAAAADBAAAAAAAAMcMAAAAAAAAyFsAAAAAAAADBAAAAAAAADUOAAAAAAAA0FsAAAAAAAADBAAAAAAAAMIJAAAAAAAA2FsAAAAAAAADBAAAAAAAADgMAAAAAAAA4FsA"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "AAAAAAADBAAAAAAAAJcMAAAAAAAA6FsAAAAAAAADBAAAAAAAAOcNAAAAAAAA8FsAAAAAAAADBAAAAAAAAPMNAAAAAAAA+FsAAAAAAAADBAAAAAAAAKIMAAAAAAAAAFwAAAAAAAADBAAAAAAAAGYNAAAAAAAACFwAAAAAAAADBAAAAAAAAA0NAAAAAAAAEFwAAAAAAAADBAAAAAAAAJEOAAAAAAAAIFwAAAAAAAADBAAAAAAAAGgRAAAAAAAAKFwAAAAAAAADBAAAAAAAAFARAAAAAAAAMFwAAAAAAAADBAAAAAAAALARAAAAAAAAEF4AAAAAAAACBAAAAQAAAAAAAAAAAAAAGF4AAAAAAAACBAAAAgAAAAAAAAAAAAAAIF4AAAAAAAACBAAAAwAAAAAAAAAAAAAAKF4AAAAAAAACBAAABAAAAAAAAAAAAAAAMF4AAAAAAAACBAAABQAAAAAAAAAAAAAAOF4AAAAAAAACBAAABgAAAAAA"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "AAAAAAAAQF4AAAAAAAACBAAABwAAAAAAAAAAAAAASF4AAAAAAAACBAAACAAAAAAAAAAAAAAAUF4AAAAAAAACBAAACQAAAAAAAAAAAAAAWF4AAAAAAAACBAAACgAAAAAAAAAAAAAAbWlzczogaWwyY3BwX2NsYXNzX2dldF9uYW1lc3BhY2UAU2luZ2xldG9uIGluc3RhbmNlIGZvdW5kIHZpYSAnJXMnOiAlcABpbDJjcHBfZG9tYWluX2dldF9hc3NlbWJsaWVzAGlsMmNwcF9maWVsZF9zZXRfdmFsdWUAaWwyY3BwX21ldGhvZF9nZXRfbmFtZQBfbWFpbgBzSW5zdGFuY2UAU2luZ2xldG9uAGlucwBpbDJjcHBfY2xhc3NfZ2V0X25hbWVzcGFjZQBDdXJyZW5jeSBjbGFzcyBub3QgZm91bmQgaW4gYW55IGFzc2VtYmx5AF9JbnN0YW5jZQBGYWlsZWQgdG8gaW5pdCBJTDJD"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "UFAgQVBJAGRsb3BlbjogJXMAZ2V0X2Fzc2VtYmxpZXMgZmFpbGVkAEZpZWxkICVzIG5vdCBmb3VuZABtaXNzOiBpbDJjcHBfaW1hZ2VfZ2V0X2NsYXNzAG1pc3M6IGlsMmNwcF9maWVsZF9zZXRfdmFsdWUAbWlzczogaWwyY3BwX2NsYXNzX2dldF9tZXRob2RzAABObyBzaW5nbGV0b24gZm91bmQgLSB3aWxsIHRyeSB0byBzZXQgb24gYWxsIGluc3RhbmNlcwBpbDJjcHBfYXNzZW1ibHlfZ2V0X2ltYWdlAGlsMmNwcF9jbGFzc19nZXRfbmFtZQBtaXNzOiBpbDJjcHBfY2xhc3NfZ2V0X2ZpZWxkX2Zyb21fbmFtZQBtaXNzOiBpbDJjcHBfY2xhc3NfZ2V0X3N0YXRpY19maWVsZF9kYXRhAFNldHRpbmcgJXMgYXQgb2Zmc2V0ICVkIHRvICVkAGlsMmNwcF9jbGFzc19n"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "ZXRfZmllbGRfZnJvbV9uYW1lAEluc3RhbmNlAF90b3RhbEhhcmRDdXJyZW5jeQA9PT0gQ1VSUkVOQ1kgSEFDSyBFTkQgPT09AFNjYW5uaW5nICV1IGFzc2VtYmxpZXMgZm9yIGN1cnJlbmN5IGNsYXNzLi4uAF9pbnN0YW5jZQBwbGF5ZXJEYXRhAG1pc3M6IGlsMmNwcF9kb21haW5fZ2V0AGlsMmNwcF9pbWFnZV9nZXRfY2xhc3MAX2N1cnJlbnQAPT09IENVUlJFTkNZIEhBQ0sgU1RBUlQgPT09AFBsYXllckRhdGEAU2F2ZQBtaXNzOiBpbDJjcHBfYXNzZW1ibHlfZ2V0X2ltYWdlAG1haW4ARmllbGQgJXM6IG9mZnNldD0lZCAobm8gaW5zdGFuY2UgdG8gc2V0KQBpbDJjcHBfZmllbGRfZ2V0X29mZnNldABzYXZlRGF0YQBfdG90YWxVcGdyYWRlQ3VycmVuY3kAaWwy"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "Y3BwX2RvbWFpbl9nZXQAbWlzczogaWwyY3BwX21ldGhvZF9nZXRfbmFtZQBfc2luZ2xldG9uAF9zYXZlAGxpYmlsMmNwcC5zbwBtaXNzOiBpbDJjcHBfY2xhc3NfZ2V0X25hbWUAbWlzczogaWwyY3BwX2RvbWFpbl9nZXRfYXNzZW1ibGllcwBpbDJjcHBfaW1hZ2VfZ2V0X2NsYXNzX2NvdW50AGRvbWFpbl9nZXQgZmFpbGVkAF9wbGF5ZXJEYXRhAHNhdmUAU2V0dGluZyBjdXJyZW5jaWVzIG9uIHNpbmdsZXRvbiBpbnN0YW5jZQBpbnN0YW5jZQBzX2luc3RhbmNlAE1haW4AbWlzczogaWwyY3BwX2ltYWdlX2dldF9jbGFzc19jb3VudABJTDJDUFAgQVBJIHJlc29sdmVkIE9LAEZPVU5EIENVUlJFTkNZIENMQVNTOiBbJXNdJXMAU2F2ZURhdGEAX3RvdGFsU29mdEN1"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "cnJlbmN5AG1pc3M6IGlsMmNwcF9maWVsZF9nZXRfb2Zmc2V0AGN1cnJlbnQAaWwyY3BwX2NsYXNzX2dldF9tZXRob2RzAGlsMmNwcF9jbGFzc19nZXRfc3RhdGljX2ZpZWxkX2RhdGEAX2lucwBDdXJyZW50AEN1cnJlbmN5SGFjawBGb3VuZCBwb3RlbnRpYWwgc2luZ2xldG9uIGZpZWxkICclcycgYXQgb2Zmc2V0ICVkAGxpYmN1cnJlbmN5aGFjay5zbyBsb2FkZWQsIHN0YXJ0aW5nIGJhY2tncm91bmQgaGFjayB0aHJlYWQAAAABGwM7XAAAAAoAAAC4AQAAdAAAAMgBAACIAAAA0AEAAJwAAADYAQAAsAAAAOwBAADEAAAACAIAANgAAAAYAgAA8AAAAGgCAAAYAQAAiAIAAEABAACMAgAAVAEAAAAAAAAQAAAAAAAAAAF6UgABfB4BGwwfABAAAAAYAAAAPAEAABAAAAAA"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "AAAAEAAAACwAAAA4AQAACAAAAAAAAAAQAAAAQAAAACwBAAAIAAAAAAAAABAAAABUAAAAIAEAABQAAAAAAAAAEAAAAGgAAAAgAQAAHAAAAAAAAAAUAAAAfAAAACgBAAAQAAAAAAAAAAAAAAAkAAAAlAAAACABAABQAAAAAEQOIEgMHRCeAp0EeAwfIEgOAN7dAAAAJAAAALwAAABIAQAAIAAAAABEDhBEDB0QngKdBFAMHxBEDgDe3QAAABAAAADkAAAAQAEAAAQAAAAAAAAAXAAAAPgAAAAwAQAAaAgAAABEDnBcDB1gkwKUBJUGlgiXCpgMmQ6aEJsSnBSeFp0YCgNYBwwfcFwOANPU1dbX2Nna29ze3UQLArAMH3BcDgDT1NXW19jZ2tvc3t0AAAAAAAAAAF8kA9UfIAPVwE8CEFUCABRfJAPVwANf1l8kA9X9//8XXyQD1WAAALTwAwCqAAIf1sADX9ZfJAPV4QMAqh8gA9UA//8Q"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "HyAD1cJNAhBJAgAUXyQD1R8gA9VDTQIQSQIAFP+DANH9ewGp/UMAkR8gA9Xh6v8Q4v//8EJsPZGAAIBSRAIAlAIAAJBCAAiR4CMAkeEDH6rjAx+qQgIAlOAHQPlEAgCU/XtBqf+DAJHAA1/W/Xu/qf0DAJGgAIBSQQIAlAUAAJTgAx+q/XvBqMADX9YBAAAU/8MB0f17Aan8bwKp+mcDqfhfBKn2VwWp9E8Gqf1DAJEfIAPVoeb/EOL///BC7DGRgACAUiICAJRTAACQaD5H+egUALRIAACQCEFH+QABP9YAIgC0SAAAkOEjAJH/BwD5CEVH+QABP9boB0D5yCEAtBQAgBKUBgARCVl0+Mn//7UfIAPVoeP/EOL///BCBDCRgACAUuMDFCoJAgCUtCAANPwDH6r1///wtVIvkVcAAJD2///w1mo6kVsAAJAEAAAUnAcAkZ8DFOtAHwBU6AdA+UkAAJApSUf5AHl8+CABP9YA//+0SAAA"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "kPgDAKoITUf5AAE/1mD+/zT5AwAq+gMfKgQAABRaBwARPwMaa6D9/1ToUkf54AMYquEDGioAAT/WIP//tGg3R/nhAxWq8wMAqgABP9aA/v+0aDdH+eADE6rhAxaqAAE/1uD9/7RoN0f54AMTquH///AhWDSRAAE/1iD9/7RIAACQ4AMTqghZR/kAAT/WSAAAkPQDAKrgAxOqCFVH+QABP9afAgDx6P//8AhVK5EfIAPVFdv/EOQDAKoDAZSa4v//8ELQOZGAAIBS4QMVqsIBAJT2///w1rowkTkAAJA5gy2RWAAAkPf///D3pjyRWgAAkAMAABQ2h0D49hcAtGg3R/ngAxOq4QMWqgABP9ZA//+0CDtH+QABP9b0AwAqgACAUuEDFariAxeq4wMWquQDFCqpAQCUSGtH+eADE6oAAT/WoP3/tBTIdPh0/f+0HyAD1RXW/xDi///wQkQlkYAAgFLhAxWq4wMWquQDFKqaAQCU4v//8ELg"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "N5GAAIBS4QMVqpUBAJRoN0f54f//8CFQL5HgAxOqAAE/1h8gA9XVTQQQVwAAkGAdALQIO0f59gMAqgABP9alAkC55AMAKh8gA9WB0v8Q4v//8EIwLpHj///wY1AvkYAAgFJ/AQCU6F5H+eADFqrhAxSq4gMVqgABP9bgAAAU4P//8ACwNZHBAIBShQEAlGA+B/ngAAC14P//8ACwNZFBAIBSfwEAlGA+B/mAFgC04f//8CGwNJF+AQCUSAAAkABBB/lADQC0YD5H+eH///Ah3CWRdwEAlEgAAJAARQf5QBQAtGA+R/nh///wITAskXABAJRIAACQAEkH+SAVALRgPkf54f//8CHgNpFpAQCUSAAAkABNB/ngFAC0YD5H+eH///AhbDGRYgEAlEgAAJAAUQf5oBQAtGA+R/nh///wIZgskVsBAJRIAACQAFUH+WAfALRgPkf54f//8CGAJ5FUAQCUSAAAkABZB/kgHwC0YD5H+eH///Ah"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "qC6RTQEAlEgAAJAANQf54B4AtGA+R/nh///wIdQzkUYBAJRIAACQADkH+aAeALRgPkf54f//8CFQJpE/AQCUSAAAkABdB/lgHgC0YD5H+eH///AhTDuROAEAlEgAAJAAYQf5IB4AtGA+R/nh///wIawmkTEBAJRIAACQAGUH+eAdALRgPkf54f//8CGwO5EqAQCUSAAAkB8gA9VBxP8QAGkH+WAdALTi///wQnQ5kYAAgFINAQCU7v7/Fx8gA9Uhw/8Q4v//8EJUN5HpAAAU4v//8EJMKZEDAAAU4v//8ELsJ5EfIAPV4cH/EMAAgFKsAAAUHyAD1WHB/xDi///wQgwxkdUAABQfIAPVwcD/EOL///BCWCuRoACAUvMAAJRoN0f54f//8CFQL5HgAxOqAAE/1oABALQIO0f5AAE/1uQDACofIAPV4b7/EOL///BCMDOR4///8GNQL5GAAIBS4gAAlGg3R/nh///wIWg6keADE6oAAT/W"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "gAEAtAg7R/kAAT/W5AMAKh8gA9XBvP8Q4v//8EIwM5Hj///wY2g6kYAAgFLRAACUaDdH+eH///AhWDSR4AMTqgABP9aADgC0CDtH+QABP9bkAwAqHyAD1aG6/xDi///wQjAzkeP///BjWDSRgACAUsAAAJRoAAAUHyAD1YG5/xDi///wQlQ2kZYAABTRAACU4wMAqh8gA9WhuP8Q4v//8EIgKZHAAIBSsgAAlI8AABQfIAPVwbf/EOL///BCnDKRiAAAFB8gA9Uht/8Q4v//8ELoOJGDAAAUHyAD1YG2/xDi///wQvApkX4AABQfIAPV4bX/EOL///BCpCmR4///8GNQL5HAAIBSmgAAlGg3R/nh///wIWg6keADE6oAAT/WgAIAtAg7R/n2AwCqAAE/1qUCQLnkAwAqHyAD1YGz/xDi///wQjAukeP///BjaDqRgACAUocAAJToXkf54AMWquEDFKriAxWqAAE/1gkAABQfIAPVwbH/"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "EOL///BCpCmR4///8GNoOpHAAIBSeQAAlGg3R/nh///wIVg0keADE6oAAT/WgAIAtAg7R/nzAwCqAAE/1qUCQLnkAwAqHyAD1WGv/xDi///wQjAukeP///BjWDSRgACAUmYAAJToXkf54AMTquEDFKriAxWqAAE/1gkAABQfIAPVoa3/EOL///BCpCmR4///8GNYNJHAAIBSWAAAlB8gA9WhrP8Q4v//8EKcL5GAAIBSUgAAlPRPRqn2V0Wp+F9EqfpnQ6n8b0Kp/XtBqf/DAZHAA1/WHyAD1eGq/xDi///wQuQ1kSEAABQfIAPVQar/EOL///BCwCSRHAAAFB8gA9Whqf8Q4v//8ELwLJEXAAAUHyAD1QGp/xDi///wQrQ6kRIAABQfIAPVYaj/EOL///BCZCqRDQAAFB8gA9XBp/8Q4v//8ELYKpEIAAAUHyAD1SGn/xDi///wQvg0kQMAABTi///wQowtkcAAgFIjAACUHyAD1QGm"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "/xDi///wQrgokcAAgFL0T0ap9ldFqfhfRKn6Z0Op/G9Cqf17Qan/wwGRFgAAFAAAAADwe7+pMAAAkBEGR/kQIjiRIAIf1h8gA9UfIAPVHyAD1TAAAJARCkf5EEI4kSACH9YwAACQEQ5H+RBiOJEgAh/WMAAAkBESR/kQgjiRIAIf1jAAAJARFkf5EKI4kSACH9YwAACQERpH+RDCOJEgAh/WMAAAkBEeR/kQ4jiRIAIf1jAAAJARIkf5EAI5kSACH9YwAACQESZH+RAiOZEgAh/WMAAAkBEqR/kQQjmRIAIf1jAAAJARLkf5EGI5kSACH9YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHQAAAAAAAADTAAAAAAAAAAEAAAAAAAAArAAAAAAAAAABAAAAAAAAAAUBAAAAAAAAAQAAAAAAAAC6AAAAAAAAAAEAAAAAAAAAywAAAAAAAAAeAAAAAAAAAAgAAAAAAAAA+///bwAAAAABAAAAAAAAAAcAAAAAAAAAoAUAAAAAAAAIAAAAAAAAAKACAAAAAAAACQAAAAAAAAAYAAAAAAAAAPn//28AAAAAHAAAAAAAAAAXAAAAAAAAAEAIAAAAAAAAAgAAAAAAAADwAAAAAAAAAAMAAAAAAAAA+F0AAAAAAAAUAAAAAAAAAAcAAAAAAAAABgAAAAAAAADQAgAAAAAAAAsAAAAAAAAAGAAAAAAAAAAFAAAA"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "AAAAAIgEAAAAAAAACgAAAAAAAAATAQAAAAAAAPX+/28AAAAAaAQAAAAAAAAZAAAAAAAAADBcAAAAAAAAGwAAAAAAAAAIAAAAAAAAABoAAAAAAAAAIFwAAAAAAAAcAAAAAAAAABAAAAAAAAAA8P//bwAAAADwAwAAAAAAAP7//28AAAAACAQAAAAAAAD///9vAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJAaAAAAAAAAkBoAAAAAAACQGgAAAAAAAJAaAAAAAAAAkBoAAAAAAACQGgAAAAAAAJAaAAAAAAAAkBoAAAAAAACQGgAAAAAAAJAaAAAAAAAA/8maO0FuZHJvaWQgKDEzOTg5ODg4LCArcGdvLCArYm9sdCwgK2x0bywgK21sZ28sIGJhc2VkIG9uIHI1NjM4ODBjKSBjbGFuZyB2ZXJzaW9uIDIxLjAuMCAoaHR0cHM6Ly9h"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "bmRyb2lkLmdvb2dsZXNvdXJjZS5jb20vdG9vbGNoYWluL2xsdm0tcHJvamVjdCA1ZTk2NjY5ZjA2MDc3MDk5YWE0MTI5MGNkYjRjNWU2ZmEwZjU5MzQ5KQAATGlua2VyOiBMTEQgMjEuMS44AGNsYW5nIHZlcnNpb24gMjEuMS44AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAEAPH/AAAAAAAAAAAAAAAAAAAAAA8AAAACAAwAUBEAAAAAAAAQAAAAAAAAABwAAAAAAAwAUBEAAAAAAAAAAAAAAAAAAB8AAAACAAwAaBEAAAAAAAAIAAAAAAAAADEAAAAAAA4AUFsAAAAAAAAAAAAAAAAAADQAAAAAAA8AIFwAAAAAAAAAAAAAAAAAADcAAAAAAA8AKFwAAAAAAAAAAAAAAAAAADoAAAAAABYAuAAAAAAAAAAAAAAAAAAAAD0AAAAAAAsA+A8AAAAAAAAAAAAAAAAAAEAA"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "AAABAAEAOAIAAAAAAACYAAAAAAAAAFMAAAAAAAEAOAIAAAAAAAAAAAAAAAAAAFYAAAAAAAEATAIAAAAAAAAAAAAAAAAAAGAAAAAAAAEARAIAAAAAAAAAAAAAAAAAAGoAAAAAAAEA0AIAAAAAAAAAAAAAAAAAAHMAAAAAAAEAUAIAAAAAAAAAAAAAAAAAAH8AAAAAAAEAkAIAAAAAAAAAAAAAAAAAADMCAAABAg4AUFsAAAAAAAAIAAAAAAAAAE8CAAACAgwAYBEAAAAAAAAIAAAAAAAAAGcCAAACAgwAcBEAAAAAAAAUAAAAAAAAAIACAAACAgwAhBEAAAAAAAAcAAAAAAAAAJQCAAACAgwAoBEAAAAAAAAQAAAAAAAAAJAAAAAEAPH/AAAAAAAAAAAAAAAAAAAAAJ8AAAACAAwAsBEAAAAAAABQAAAAAAAAAKcAAAAAAAwAsBEAAAAAAAAAAAAAAAAAAKoAAAACAAwAABIAAAAAAAAg"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "AAAAAAAAALYAAAACAAwAJBIAAAAAAABoCAAAAAAAAMcAAAABABUAeJ4AAAAAAAAIAAAAAAAAAMwAAAABABUAgJ4AAAAAAAAIAAAAAAAAANkAAAABABUAiJ4AAAAAAAAIAAAAAAAAAPEAAAABABUAoJ4AAAAAAAAIAAAAAAAAAAMBAAABABUAaJ4AAAAAAAAIAAAAAAAAAB8BAAABABUAkJ4AAAAAAAAIAAAAAAAAADQBAAABABUAmJ4AAAAAAAAIAAAAAAAAAEwBAAABABUAsJ4AAAAAAAAIAAAAAAAAAGIBAAABABUAqJ4AAAAAAAAIAAAAAAAAAHMBAAABAA4AWFsAAAAAAADIAAAAAAAAAJsBAAABABUAcJ4AAAAAAAAIAAAAAAAAAK4BAAABABUA0J4AAAAAAAAIAAAAAAAAAMwBAAABABQAYJ4AAAAAAAAEAAAAAAAAANUBAAABABUAuJ4AAAAAAAAIAAAAAAAAAOcBAAABABUA"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "wJ4AAAAAAAAIAAAAAAAAAPsBAAABABUAyJ4AAAAAAAAIAAAAAAAAAA0CAAAAAAkAHA8AAAAAAAAAAAAAAAAAABACAAAAABUAaJ4AAAAAAAAAAAAAAAAAABMCAAAAAA4AWFsAAAAAAAAAAAAAAAAAABYCAAAAABQAYJ4AAAAAAAAAAAAAAAAAABkCAAAAABAAMFwAAAAAAAAAAAAAAAAAABwCAAAAABYAuAAAAAAAAAAAAAAAAAAAAB8CAAAAAAsA+A8AAAAAAAAAAAAAAAAAACICAAABAAsA+A8AAAAAAAAEAAAAAAAAADACAAAAAAsA+A8AAAAAAAAAAAAAAAAAADIDAAAAAhEAOFwAAAAAAAAAAAAAAAAAAEACAAASAAAAAAAAAAAAAAAAAAAAAAAAAIcCAAASAAAAAAAAAAAAAAAAAAAAAAAAAKMCAAASAAAAAAAAAAAAAAAAAAAAAAAAALUCAAASAAAAAAAAAAAAAAAAAAAAAAAA"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "AMkCAAASAAAAAAAAAAAAAAAAAAAAAAAAANgCAAASAAAAAAAAAAAAAAAAAAAAAAAAAOcCAAASAAAAAAAAAAAAAAAAAAAAAAAAAO0CAAASAAwAIBIAAAAAAAAEAAAAAAAAAB0DAAASAAAAAAAAAAAAAAAAAAAAAAAAACQDAAASAAAAAAAAAAAAAAAAAAAAAAAAACoDAAASAAAAAAAAAAAAAAAAAAAAAAAAAAAubm90ZS5hbmRyb2lkLmlkZW50AC5keW5zeW0ALmdudS52ZXJzaW9uAC5nbnUudmVyc2lvbl9yAC5nbnUuaGFzaAAuZHluc3RyAC5yZWxhLmR5bgAucmVsYS5wbHQALnJvZGF0YQAuZWhfZnJhbWVfaGRyAC5laF9mcmFtZQAudGV4dAAucGx0AC5kYXRhLnJlbC5ybwAuZmluaV9hcnJheQAuaW5pdF9hcnJheQAuZHluYW1pYwAuZ290LnBsdAAucmVscm9fcGFkZGlu"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "ZwAuZGF0YQAuYnNzAC5jb21tZW50AC5zeW10YWIALnNoc3RydGFiAC5zdHJ0YWIAAGNydGJlZ2luX3NvLmMAX19vbl9kbGNsb3NlACR4AF9fb25fZGxjbG9zZV9sYXRlACRkACRkACRkACRkACRkAG5vdGVfYW5kcm9pZF9pZGVudAAkZABub3RlX2RhdGEAbm90ZV9uYW1lAG5vdGVfZW5kAG5ka192ZXJzaW9uAG5ka19idWlsZF9udW1iZXIAY3VycmVuY3loYWNrLmMAb25fbG9hZAAkeABoYWNrX3RocmVhZABkb19jdXJyZW5jeV9oYWNrAGhsaWIAcF9kb21haW5fZ2V0AHBfZG9tYWluX2dldF9hc3NlbWJsaWVzAHBfaW1hZ2VfZ2V0X2NsYXNzAHBfY2xhc3NfZ2V0X2ZpZWxkX2Zyb21fbmFtZQBwX2Fzc2VtYmx5X2dldF9pbWFnZQBwX2ltYWdlX2dldF9jbGFzc19j"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "b3VudABwX2NsYXNzX2dldF9uYW1lc3BhY2UAcF9jbGFzc19nZXRfbmFtZQBmaW5kX3NpbmdsZXRvbl9pbnN0YW5jZS5zaW5nbGV0b25fbmFtZXMAcF9maWVsZF9nZXRfb2Zmc2V0AHBfY2xhc3NfZ2V0X3N0YXRpY19maWVsZF9kYXRhAE1BWF9DVVJSAHBfZmllbGRfc2V0X3ZhbHVlAHBfY2xhc3NfZ2V0X21ldGhvZHMAcF9tZXRob2RfZ2V0X25hbWUAJGQAJGQAJGQAJGQAJGQAJGQAJGQAX19GUkFNRV9FTkRfXwAkZABfX2Rzb19oYW5kbGUAX19jeGFfZmluYWxpemUAX19lbXV0bHNfdW5yZWdpc3Rlcl9rZXkAX19hdGV4aXRfaGFuZGxlcl93cmFwcGVyAGF0ZXhpdABfX2N4YV9hdGV4aXQAcHRocmVhZF9hdGZvcmsAX19yZWdpc3Rlcl9hdGZvcmsAX19hbmRyb2lk"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "X2xvZ19wcmludABwdGhyZWFkX2NyZWF0ZQBwdGhyZWFkX2RldGFjaABzbGVlcABKYXZhX2NvbV9haW1fRXh0cmVtZUFjdGl2aXR5X25hdGl2ZUN1cnJlbmN5SGFjawBkbG9wZW4AZGxzeW0AZGxlcnJvcgBfRFlOQU1JQwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAHAAAAAgAAAAAAAAA4AgAAAAAAADgCAAAAAAAAmAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAVAAAACwAAAAIAAAAAAAAA0AIAAAAAAADQAgAAAAAAACABAAAAAAAABgAAAAEAAAAIAAAAAAAAABgAAAAAAAAAHQAAAP///28CAAAAAAAAAPADAAAAAAAA8AMAAAAAAAAYAAAAAAAAAAIAAAAAAAAAAgAA"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "AAAAAAACAAAAAAAAACoAAAD+//9vAgAAAAAAAAAIBAAAAAAAAAgEAAAAAAAAYAAAAAAAAAAGAAAAAwAAAAQAAAAAAAAAAAAAAAAAAAA5AAAA9v//bwIAAAAAAAAAaAQAAAAAAABoBAAAAAAAACAAAAAAAAAAAgAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAQwAAAAMAAAACAAAAAAAAAIgEAAAAAAAAiAQAAAAAAAATAQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAEsAAAAEAAAAAgAAAAAAAACgBQAAAAAAAKAFAAAAAAAAoAIAAAAAAAACAAAAAAAAAAgAAAAAAAAAGAAAAAAAAABVAAAABAAAAEIAAAAAAAAAQAgAAAAAAABACAAAAAAAAPAAAAAAAAAAAgAAABIAAAAIAAAAAAAAABgAAAAAAAAAXwAAAAEAAAAyAAAAAAAAADAJAAAAAAAAMAkAAAAAAABmBgAAAAAAAAAA"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "AAAAAAAAAQAAAAAAAAABAAAAAAAAAGcAAAABAAAAAgAAAAAAAACYDwAAAAAAAJgPAAAAAAAAXAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAB1AAAAAQAAAAIAAAAAAAAA+A8AAAAAAAD4DwAAAAAAAFgBAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAfwAAAAEAAAAGAAAAAAAAAFARAAAAAAAAUBEAAAAAAAA8CQAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAIUAAAABAAAABgAAIAAAAACQGgAAAAAAAJAaAAAAAAAAwAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAACKAAAAAQAAAAMAAAAAAAAAUFsAAAAAAABQGwAAAAAAANAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAlwAAAA8AAAADAAAAAAAAACBcAAAAAAAAIBwAAAAAAAAQ"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "AAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAKMAAAAOAAAAAwAAAAAAAAAwXAAAAAAAADAcAAAAAAAACAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAACvAAAABgAAAAMAAAAAAAAAOFwAAAAAAAA4HAAAAAAAAMABAAAAAAAABgAAAAAAAAAIAAAAAAAAABAAAAAAAAAAuAAAAAEAAAADAAAAAAAAAPhdAAAAAAAA+B0AAAAAAABoAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAMEAAAAIAAAAAwAAAAAAAABgXgAAAAAAAGAeAAAAAAAAoAEAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAADQAAAAAQAAAAMAAAAAAAAAYJ4AAAAAAABgHgAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAA1gAAAAgAAAADAAAAAAAAAGieAAAAAAAA"
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            const-string v5, "ZB4AAAAAAABwAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAANsAAAABAAAAMAAAAAAAAAAAAAAAAAAAAGQeAAAAAAAA4QAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAADkAAAAAgAAAAAAAAAAAAAAAAAAAAAAAABIHwAAAAAAAAAGAAAAAAAAGQAAADUAAAAIAAAAAAAAABgAAAAAAAAA7AAAAAMAAAAAAAAAAAAAAAAAAAAAAAAASCUAAAAAAAD+AAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAPYAAAADAAAAAAAAAAAAAAAAAAAAAAAAAEYmAAAAAAAAOwMAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAA="
            invoke-virtual {v3, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
            pop-object
            invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
            move-result-object v3
            const/4 v5, 0x0
            invoke-static {v3, v5}, Landroid/util/Base64;->decode(Ljava/lang/String;I)[B
            move-result-object v3
            new-instance v5, Ljava/io/FileOutputStream;
            invoke-direct {v5, v4}, Ljava/io/FileOutputStream;-><init>(Ljava/io/File;)V
            invoke-virtual {v5, v3}, Ljava/io/FileOutputStream;->write([B)V
            invoke-virtual {v5}, Ljava/io/FileOutputStream;->close()V
            invoke-virtual {v4}, Ljava/io/File;->getAbsolutePath()Ljava/lang/String;
            move-result-object v3
            const/4 v5, 0x1
            invoke-static {v3, v5}, Ljava/io/File;->setExecutable(Ljava/lang/String;Z)Z
            invoke-virtual {v4}, Ljava/io/File;->getAbsolutePath()Ljava/lang/String;
            move-result-object v3
            invoke-static {v3}, Ljava/lang/Runtime;->load(Ljava/lang/String;)V
            :currency_hack_loaded
        """.trimIndent())
    }
}
